server:
  ssl:
    enabled: false
  tomcat:
    max-http-form-post-size: 100MB  #请求参数长度

spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  servlet :
    multipart:
      enabled: true
      max-file-size: 1024MB # 单个文件上传大小
      max-request-size: 1024MB # 总上传大小
